cf_comment:
    resource: "@CFCommentBundle/Resources/config/routing.yml"
    prefix:   /

cf_user:
    resource: "@CFUserBundle/Resources/config/routing.yml"

cf_main:
    resource: "@CFMainBundle/Resources/config/routing.yml"
    prefix:   /