services:
    sonata.admin.projet:
        class: CF\MainBundle\Admin\ProjetAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Projets", label: "Projet" }
        arguments:
            - ~
            - CF\MainBundle\Entity\Projet
            - ~
        calls:
            - [ setTranslationDomain, [CFMainBundle]]

    sonata.admin.projet_accueil:
        class: CF\MainBundle\Admin\ProjetAccueilAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Projets", label: "Accueil" }
        arguments:
            - ~
            - CF\MainBundle\Entity\ProjetAccueil
            - ~
        calls:
            - [ setTranslationDomain, [CFMainBundle]]