cf_main_homepage:
    path:     /
    defaults: { _controller: CFMainBundle:Page:index }

cf_main_project:
    path:     /projet/{id}
    defaults: { _controller: CFMainBundle:Project:show }
    requirements:
        _method: GET
        id: \d+

cf_main_addProjects:
    path:     /projet/creer/
    defaults: { _controller: CFMainBundle:Project:add }
    requirements:
        _method: GET|POST

cf_main_projects:
    resource: routing/projects.yml
    prefix: /projets

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }