cf_main_allProjects:
    path:     /tous
    defaults: { _controller: CFMainBundle:Project:showAll }

cf_main_recherche:
    path:   /recherche
    defaults: { _controller: CFMainBundle:Recherche:search }

cf_main_rechercheUpdate:
    path:   /recherche/update
    defaults: { _controller: CFMainBundle:Recherche:updateSearch }