cf_main_allProjects:
    path:     /categorie/{nom}
    defaults: { _controller: CFMainBundle:Project:showAll ,nom:'All'}

cf_main_endingProjects:
    path:     /bientot-fini/
    defaults: { _controller: CFMainBundle:Project:showEnding }

cf_main_newProjects:
    path:     /nouveaux/
    defaults: { _controller: CFMainBundle:Project:showNew }

cf_main_highlightProjects:
    path:     /populaire/
    defaults: { _controller: CFMainBundle:Project:showHighlights }

